apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: sayinmehmet47/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/commments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: sayinmehmet47/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayinmehmet47/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
